const initialCars = [
  {
    id: "car-001",
    title: "Porsche 911 GT3 RS",
    make: "Porsche",
    model: "911 GT3 RS",
    year: 2024,
    price: 241300,
    mileage: 450,
    fuelType: "Petrol",
    transmission: "Automatic (PDK)",
    bodyType: "Coupe",
    engine: "4.0L Naturally Aspirated Flat-6",
    horsepower: 518,
    zeroToSixty: "3.0s",
    topSpeed: "184 mph",
    drivetrain: "RWD",
    exteriorColor: "Ice Grey Metallic",
    interiorColor: "Black Leather / Race-Tex",
    status: "Available",
    category: "Supercar",
    featured: true,
    description: "The Porsche 911 GT3 RS is designed without compromise for maximum performance. Incorporating motorsport aerodynamics and lightweight construction with active DRS and 518 HP.",
    features: ["Active Aerodynamics & DRS", "Carbon Fiber Bucket Seats", "PCCB Ceramic Brakes", "Weissach Package"],
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-002",
    title: "Tesla Model S Plaid",
    make: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    price: 109990,
    mileage: 1200,
    fuelType: "Electric",
    transmission: "Direct Drive",
    bodyType: "Sedan",
    engine: "Tri-Motor All-Wheel Drive",
    horsepower: 1020,
    zeroToSixty: "1.99s",
    topSpeed: "200 mph",
    drivetrain: "AWD",
    exteriorColor: "Ultra Red",
    interiorColor: "White & Carbon Fiber",
    status: "Available",
    category: "Electric",
    featured: true,
    description: "Tri-Motor All-Wheel Drive with torque vectoring and 1,020 hp total output provides mind-bending hypercar performance with luxury sedan practicality.",
    features: ["Full Self-Driving", "Yoke Steering", "22-Speaker 960W Audio", "Carbon Rotors"],
    images: [
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-003",
    title: "Lamborghini Huracán STO",
    make: "Lamborghini",
    model: "Huracán STO",
    year: 2024,
    price: 334700,
    mileage: 300,
    fuelType: "Petrol",
    transmission: "7-Speed Dual-Clutch",
    bodyType: "Coupe",
    engine: "5.2L Naturally Aspirated V10",
    horsepower: 631,
    zeroToSixty: "3.0s",
    topSpeed: "192 mph",
    drivetrain: "RWD",
    exteriorColor: "Verde Citrea",
    interiorColor: "Alcantara Nero Cosmus",
    status: "Available",
    category: "Supercar",
    featured: true,
    description: "Super Trofeo Omologata. A road-homologated super sports car inspired by the racing heritage of Lamborghini Squadra Corse's one-make race series.",
    features: ["Cofango One-Piece Front Hood", "Magnesium Wheels", "CCMR Braking System", "Telemetry System"],
    images: [
      "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-004",
    title: "Ferrari F8 Tributo",
    make: "Ferrari",
    model: "F8 Tributo",
    year: 2023,
    price: 325000,
    mileage: 1800,
    fuelType: "Petrol",
    transmission: "7-Speed F1 Dual-Clutch",
    bodyType: "Coupe",
    engine: "3.9L Twin-Turbo V8",
    horsepower: 710,
    zeroToSixty: "2.9s",
    topSpeed: "211 mph",
    drivetrain: "RWD",
    exteriorColor: "Rosso Corsa",
    interiorColor: "Nero Leather with Giallo Stitching",
    status: "Available",
    category: "Supercar",
    featured: true,
    description: "A tribute to the most powerful V8 in Ferrari history. 710 horsepower of pure Italian emotion, S-Duct aerodynamic efficiency, and Side Slip Control 6.1.",
    features: ["Scuderia Ferrari Shields", "Carbon Driver Zone", "Passenger Display", "Titanium Exhaust"],
    images: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-005",
    title: "BMW M5 CS",
    make: "BMW",
    model: "M5 CS",
    year: 2023,
    price: 142000,
    mileage: 3400,
    fuelType: "Petrol",
    transmission: "8-Speed M Steptronic",
    bodyType: "Sedan",
    engine: "4.4L Twin-Turbo V8",
    horsepower: 627,
    zeroToSixty: "2.9s",
    topSpeed: "190 mph",
    drivetrain: "M xDrive AWD",
    exteriorColor: "Frozen Deep Green Metallic",
    interiorColor: "Black Leather with Red Accents",
    status: "Available",
    category: "Luxury",
    featured: true,
    description: "The most powerful production BMW M car. 627 HP, weight reduction of 154 lbs, gold-bronze accents, and 4 individual M Carbon bucket seats.",
    features: ["Gold-Bronze Forged Wheels", "M Carbon Bucket Seats", "Yellow LED Headlights", "Carbon Ceramic Brakes"],
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-006",
    title: "Audi R8 V10 Performance",
    make: "Audi",
    model: "R8 V10",
    year: 2023,
    price: 209700,
    mileage: 2800,
    fuelType: "Petrol",
    transmission: "7-Speed Dual-Clutch",
    bodyType: "Coupe",
    engine: "5.2L FSI V10",
    horsepower: 602,
    zeroToSixty: "3.1s",
    topSpeed: "205 mph",
    drivetrain: "quattro AWD",
    exteriorColor: "Kemora Gray Metallic",
    interiorColor: "Express Red Fine Nappa",
    status: "Available",
    category: "Supercar",
    featured: false,
    description: "The iconic finale of Audi's naturally aspirated V10 era. Pure acoustic euphoria combined with legendary quattro performance.",
    features: ["Bang & Olufsen 3D Sound", "Carbon Exterior Package", "Audi Virtual Cockpit", "Laser Lights"],
    images: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-007",
    title: "Ford Mustang Shelby GT500",
    make: "Ford",
    model: "Shelby GT500",
    year: 2023,
    price: 98500,
    mileage: 2100,
    fuelType: "Petrol",
    transmission: "7-Speed Tremec Dual-Clutch",
    bodyType: "Coupe",
    engine: "5.2L Supercharged Cross-Plane V8",
    horsepower: 760,
    zeroToSixty: "3.3s",
    topSpeed: "180 mph",
    drivetrain: "RWD",
    exteriorColor: "Grabber Blue Metallic",
    interiorColor: "Recaro Leather Bucket Seats",
    status: "Available",
    category: "Sports",
    featured: false,
    description: "The most powerful street-legal Ford ever built. 760 horsepower supercharged V8 coupled with lightning-fast Tremec dual-clutch transmission.",
    features: ["Carbon Fiber Track Pack", "MagneRide Damping", "Brembo 6-Piston Brakes", "Launch Control"],
    images: [
      "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-008",
    title: "Porsche Taycan Turbo S",
    make: "Porsche",
    model: "Taycan Turbo S",
    year: 2024,
    price: 194900,
    mileage: 600,
    fuelType: "Electric",
    transmission: "2-Speed Automatic Rear",
    bodyType: "Sedan",
    engine: "Dual Permanent Magnet Motors",
    horsepower: 750,
    zeroToSixty: "2.6s",
    topSpeed: "161 mph",
    drivetrain: "AWD",
    exteriorColor: "Neptune Blue",
    interiorColor: "Olea Club Leather",
    status: "Available",
    category: "Electric",
    featured: false,
    description: "Pure electric soul with undeniable Porsche DNA. Up to 750 hp overboost with Launch Control and 800-volt charging architecture.",
    features: ["Electric Sport Sound", "PDCC Sport Active Roll", "Burmester 3D High-End", "Passenger Screen"],
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-009",
    title: "Range Rover SV P530",
    make: "Land Rover",
    model: "Range Rover SV",
    year: 2024,
    price: 218000,
    mileage: 1500,
    fuelType: "Hybrid",
    transmission: "8-Speed Automatic",
    bodyType: "SUV",
    engine: "4.4L Twin-Turbo V8 MHEV",
    horsepower: 523,
    zeroToSixty: "4.4s",
    topSpeed: "162 mph",
    drivetrain: "AWD",
    exteriorColor: "Sunset Gold Satin",
    interiorColor: "Perlino Near-Aniline Leather",
    status: "Available",
    category: "SUV",
    featured: false,
    description: "The pinnacle of British luxury and capability. SV Bespoke execution, executive class rear seating with deployed club table, and active noise cancellation.",
    features: ["SV Signature Suite 4-Seat", "Hot Stone Massage Seats", "Meridian 1600W Audio", "All-Wheel Steering"],
    images: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-010",
    title: "Chevrolet Corvette Z06",
    make: "Chevrolet",
    model: "Corvette Z06",
    year: 2024,
    price: 125000,
    mileage: 800,
    fuelType: "Petrol",
    transmission: "8-Speed Dual-Clutch",
    bodyType: "Coupe",
    engine: "5.5L LT6 Naturally Aspirated Flat-Plane V8",
    horsepower: 670,
    zeroToSixty: "2.6s",
    topSpeed: "195 mph",
    drivetrain: "RWD",
    exteriorColor: "Accelerate Yellow",
    interiorColor: "Jet Black Competition Seats",
    status: "Available",
    category: "Sports",
    featured: false,
    description: "The highest horsepower naturally aspirated V8 in production. Revs to an astonishing 8,600 RPM with supercar-slaying track performance.",
    features: ["Z07 Performance Package", "Carbon Fiber Aero Package", "Carbon Fiber Wheels", "Brembo Carbon Ceramic"],
    images: [
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-011",
    title: "Mercedes-AMG GT Black Series",
    make: "Mercedes-Benz",
    model: "AMG GT Black Series",
    year: 2022,
    price: 389000,
    mileage: 950,
    fuelType: "Petrol",
    transmission: "7-Speed Dual-Clutch",
    bodyType: "Coupe",
    engine: "4.0L Flat-Plane V8 Twin-Turbo",
    horsepower: 720,
    zeroToSixty: "3.1s",
    topSpeed: "202 mph",
    drivetrain: "RWD",
    exteriorColor: "AMG Magmabeam Orange",
    interiorColor: "Black Nappa Leather / DINAMICA",
    status: "Available",
    category: "Supercar",
    featured: false,
    description: "Nürburgring record setter. Features 720 HP flat-plane V8, double rear wing active aero, and race suspension.",
    features: ["Adjustable Carbon Front Splitter", "AMG Track Package", "Carbon Bucket Seats", "9-Level Traction Control"],
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80"
    ]
  },
  {
    id: "car-012",
    title: "Nissan GT-R Nismo",
    make: "Nissan",
    model: "GT-R Nismo",
    year: 2024,
    price: 221000,
    mileage: 500,
    fuelType: "Petrol",
    transmission: "6-Speed Dual-Clutch",
    bodyType: "Coupe",
    engine: "3.8L Twin-Turbo V6",
    horsepower: 600,
    zeroToSixty: "2.7s",
    topSpeed: "205 mph",
    drivetrain: "ATTESA E-TS AWD",
    exteriorColor: "Stealth Gray",
    interiorColor: "Recaro Carbon Bucket Seats",
    status: "Available",
    category: "Sports",
    featured: false,
    description: "Godzilla at its ultimate evolution. GT3 turbochargers, carbon fiber roof, hood, fenders, and Brembo carbon ceramic brakes.",
    features: ["Nismo Carbon Aero Pack", "RAYS 20\" Forged Wheels", "Brembo Carbon Ceramic", "Takumi Handbuilt Engine"],
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80"
    ]
  }
];

module.exports = initialCars;
